name: 'RSSを取得'
description: 'RSSからファイルを追加するよ'
inputs:
  url:
    description: 'RSSのURL'
    required: true
    default: 'https://anchor.fm/s/ca24318/podcast/rss'
outputs:
  title:
    description: 'エピソードのタイトル'
  link:
    description: "エピソードのembed URL"
  content:
    description: "エピソードの説明"
  date:
    description: "エピソードのリリース時間"
runs:
  using: 'node12'
  main: 'dist/index.js'
