name: RSS Feed Parser

on:
  "push"

jobs:
  rss-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: |
          const Parser = require('rss-parser');
          const parser = new Parser();
          const feed = await parser.parseURL('https://example.com/feed.xml');

          feed.items.forEach(item => {
            console.log(item.title);
            console.log(item.link);
          });

